import { SiteFooter, SiteHeader } from "../components/SiteChrome";

const services = [
  ["01", "Leasing & placement", "Thoughtful marketing, applicant coordination, and lease support designed to find the right resident for each home."],
  ["02", "Rent collection", "Consistent rent collection, payment follow-up, and organized records that help keep property income on schedule."],
  ["03", "Tenant communication", "A dependable point of contact for resident questions, notices, requests, and the everyday details of renting."],
  ["04", "Maintenance coordination", "Prompt assessment, vendor scheduling, and repair follow-through, with clear updates for both owners and tenants."],
  ["05", "Monthly owner statements", "Clear monthly statements summarizing rent received, property expenses, and other activity owners need to review."],
  ["06", "Lease tracking", "Active tracking of lease dates, renewals, notices, and key documents so important deadlines do not get overlooked."],
  ["07", "Condo-management interaction", "Coordination with condominium management on building requirements, access, move procedures, and property-related requests."],
  ["08", "Emergency coordination", "A clear response path for urgent property issues, including resident communication, vendor dispatch, and owner updates."],
];

export default function PropertyManagement() {
  return <main><SiteHeader /><section className="subpage-hero management-hero"><p className="eyebrow light"><span /> Property management</p><h1>More freedom.<br /><em>Fewer loose ends.</em></h1><p>Hands-on rental management that protects your time, supports your residents, and keeps you close to what matters.</p><a className="button button-light" href="mailto:management@jhkproperties.com?subject=Property%20management%20inquiry" data-goatcounter-click="management-discuss-property">Discuss your property <span>↗</span></a></section><section className="section services-section"><div className="section-heading services-heading"><p className="eyebrow"><span /> Full-service support</p><h2>Care for the property. Clarity for the owner.</h2><p>We bring the moving parts of rental ownership together, with an approach shaped around your property and priorities.</p></div><div className="services-grid">{services.map(([number,title,text]) => <article className="service-card" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="section owner-section"><div className="owner-copy"><p className="eyebrow light"><span /> Start a conversation</p><h2>Tell us about your property.</h2><p>Whether you own one rental or a growing portfolio, we would be glad to learn what you need and talk through how JHK can help.</p><a className="button button-light" href="mailto:management@jhkproperties.com?subject=Property%20management%20inquiry" data-goatcounter-click="management-request-consultation">Request a consultation <span>↗</span></a></div><aside className="owner-details"><p>Helpful details</p><h3>What to include in your note</h3><ul><li>Property location and type</li><li>Number of units</li><li>Current occupancy</li><li>What you would like help managing</li></ul><a href="mailto:management@jhkproperties.com?subject=Property%20management%20inquiry" data-goatcounter-click="management-email-link">management@jhkproperties.com</a></aside></section><SiteFooter /></main>;
}
